import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gsocind
 */
public class confirmationFrame extends javax.swing.JFrame {

    /**
     * Creates new form confirmationFrame
     */
    public confirmationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NBA TICKET CONFIRMATION");
        setMinimumSize(new java.awt.Dimension(490, 690));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FINAL NBA TICKET :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 313, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nba.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 80, 272, 117);

        jButton1.setText("SAVE AND PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 620, 140, 21);

        jButton2.setText("BOOK NBA DESTINATION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 620, 180, 21);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NAME:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 220, 130, 40);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("<html>PRICE:<br>(in $$$)</html>");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 270, 60, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SEATS BOOKED:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 320, 100, 13);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BOOKING ID:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 360, 100, 30);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 220, 220, 30);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 270, 220, 30);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(180, 320, 220, 30);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(180, 370, 220, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lebron.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 410, 490, 200);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 620, 55, 21);

        jLabel1.setBackground(new java.awt.Color(51, 0, 0));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 490, 610);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        jLabel4.setText("CLICK THE BACKGROUND");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 10, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try
{

String n1=jTextField5.getText();
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","student");
Statement stmt=con.createStatement();
String query="update air set name='"+n1+"' where slno=100;";


stmt.executeUpdate(query);

con.close();
stmt.close();

}
             catch(Exception e)
            {
            JOptionPane.showMessageDialog(null,"Error");
            }
new airplaneIntroFrame().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try
{

Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","student");
Statement stmt=con.createStatement();
String quer="update user set matches=null,date=null,name=null,emailid=null,seat=null,noofseats=null,price=null,seats=null;";

System.out.println(quer);
stmt.executeUpdate(quer);

con.close();
stmt.close();
}
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null,"Error");
            }
JOptionPane.showMessageDialog(null,"Details Saved");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
JOptionPane.showMessageDialog(null,"THANKS FOR BOOKING NBA TICKETS");
System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      if(jTextField5.getText().equals(""))
{
try
{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","student");

Statement stmt=con.createStatement();
String quer="select name,price,seats from user where slno=100";

System.out.println(quer);
ResultSet rs=stmt.executeQuery(quer);

if(rs.next())
{

String n1=rs.getString("name");
String n2=rs.getString("price");
String n3=rs.getString("seats");

jTextField5.setText(""+n1);
jTextField6.setText(""+n2);
jTextField7.setText(""+n3);

}

rs.close();
con.close();
stmt.close();

}
             catch(Exception e)
            {
            JOptionPane.showMessageDialog(null,"Error");
            }

}
jTextField8.setText(""+Math.round(Math.random()*100000));     
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
int n = Integer.parseInt(jTextField6.getText());       
if((n>=600))
{
JOptionPane.showMessageDialog(null,"You have won 1500 NBA points. NBA points can be used to book NBA flights, or to buy exclusive merchandise from NBAstore.in");    
}  
if((n>300)&&(n<=500)) 
{
JOptionPane.showMessageDialog(null,"You have won 700 NBA points. NBA points can be used to book NBA flights, or to buy exclusive merchandise from NBAstore.in");
}
if((n>50)&&(n<=300)) 
{
JOptionPane.showMessageDialog(null,"You have won 500 NBA points. NBA points can be used to book NBA flights, or to buy exclusive merchandise from NBAstore.in");
}   
    }//GEN-LAST:event_jLabel13MouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirmationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
