import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class flightFrame extends javax.swing.JFrame {

    /**
     * Creates new form flightFrame
     */
    public flightFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AIR TICKET BOOKING");
        setMinimumSize(new java.awt.Dimension(1150, 665));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Departure Airport :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(77, 150, 130, 31);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 150, 150, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Arrival Airport :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(419, 160, 110, 17);

        jTextField2.setEditable(false);
        jTextField2.setText("CHARLOTTE");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(550, 150, 170, 30);

        jButton1.setText("SEARCH FLIGHTS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(810, 140, 200, 50);

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel3.setText("AIR TICKET RESERVATION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 20, 300, 60);

        jLabel7.setText("ENTER NBA CREDITS :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 80, 160, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(230, 330, 170, 40);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(480, 80, 157, 34);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Enter number of seats:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 340, 164, 17);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(670, 330, 187, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Place of departure:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 400, 140, 29);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Airlines Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 360, 134, 17);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(230, 400, 170, 38);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("CONFIRM BOOKING THROUGH POINTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 510, 340, 72);

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FLIGHT NO", "AIRLINES", "DEPARTURE", "ARRIVAL", "DEPARTURE TIME", "ARRIVAL TIME", "DURATION", "SEATS AVAILABLE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 200, 920, 119);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Flight NO:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(470, 420, 140, 17);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(670, 420, 190, 40);

        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("CALCULATE PRICE(IN DOLLARS)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 520, 240, 60);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(280, 530, 170, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flight.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1130, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int res = JOptionPane.showConfirmDialog(null,"Confirm payment of $"+price+" for flight ticket using NBA points"); 
if(res==JOptionPane.YES_OPTION)
{    
try
{

String n1=jTextField6.getText();
String n2=jTextField5.getText();
int n3 = Integer.parseInt(jTextField3.getText());
String n4=jTextField7.getText();
int n5 = Integer.parseInt(jTextField8.getText());

Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","student");
Statement stmt=con.createStatement();
String query="update air set airliner='"+n1+"',departure='"+n2+"',seats='"+n3+"',flightno='"+n4+"',price='"+n5+"' where slno=100;";


stmt.executeUpdate(query);

con.close();
stmt.close();

}
             catch(Exception e)
            {
            JOptionPane.showMessageDialog(null,"ERROR");
            }
new flightConfirmation().setVisible(true);
dispose();
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
DefaultTableModel mod = (DefaultTableModel)jTable1.getModel();
int n = jTable1.getSelectedRow();
jTextField6.setText(mod.getValueAt(n,1).toString());
jTextField5.setText(mod.getValueAt(n,2).toString());        
jTextField7.setText(mod.getValueAt(n, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked


    }//GEN-LAST:event_jLabel9MouseClicked
int price = 0 ;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int n = Integer.parseInt(jTextField3.getText());
if(n>4)
{
  JOptionPane.showMessageDialog(null,"Maximum Seats per person is 4");  
}  
else{
price = 75*n;
jTextField8.setText(""+price+"");
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel mod = (DefaultTableModel)jTable1.getModel();
String a=jTextField1.getText();
if(a.equalsIgnoreCase("bangalore")||(a.equalsIgnoreCase("sydney")||(a.equalsIgnoreCase("auckland")||(a.equalsIgnoreCase("johannesburg")||a.equalsIgnoreCase("london")))))
{
    if(mod.getRowCount()==0)
{
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","student");
Statement stmt = con.createStatement();
String query = "SELECT * FROM flight;";
ResultSet rs = stmt.executeQuery(query);
while(rs.next())
{
    String n1 = rs.getString("flight_no");
    String n2 = rs.getString("airliner_name");
    String n3 = rs.getString("departure");
    String n4 = rs.getString("arrival");
    String n5 = rs.getString("departure_time");
    String n6 = rs.getString("arrival_time");
    String n7 = rs.getString("duration");
    String n8 = rs.getString("seats");

    mod.addRow(new Object[]{n1,n2,n3,n4,n5,n6,n7,n8});
}
rs.close();
con.close();
stmt.close();
}
catch(Exception e )
{
    
    JOptionPane.showMessageDialog(null, "error");}

}
}
else
{
    JOptionPane.showMessageDialog(this,"Flights are not available from this destination");
}





/*
        {
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","student");
Statement stmt = con.createStatement();
String query = "SELECT * FROM flight;";
ResultSet rs = stmt.executeQuery(query);
while(rs.next())
{
    String n1 = rs.getString("flight_no");
    String n2 = rs.getString("airliner_name");
    String n3 = rs.getString("departure");
    String n4 = rs.getString("arrival");
    String n5 = rs.getString("departure_time");
    String n6 = rs.getString("arrival_time");
    String n7 = rs.getString("duration");
    String n8 = rs.getString("seats");

    mod.addRow(new Object[]{n1,n2,n3,n4,n5,n6,n7,n8});
}
rs.close();
con.close();
stmt.close();
}
catch(Exception e )
{
    
    JOptionPane.showMessageDialog(null, "error");}

}

*/

       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flightFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
